### ISSUE TITLE
Original manual + media.

### ISSUE THREAD

**Issue by ravn** [Oric4ever/Turbo-Modula-2-Reloaded#1]
Hi.

I bought an used copy of Borland Modula 2 CP/M-80 (manual and media) for our first year computer science projects back in the 90'es, and not used it since but held on to it for nostalgia.   I just saw your project, and thought you might be interested in it.

German cover, English text. 5,25 inch media.

![IMG_8288](https://user-images.githubusercontent.com/117042/102703804-e6748400-4273-11eb-86a0-00dd5fb14fc3.jpeg)

**Comment by Oric4ever** [comment]
Hello Thorbjørn,

that's very nice of you, I am really interested indeed by the manual...

Currently I have a pdf scan downloaded from http://www.cpcwiki.eu/imgs/6/64/Borland_Turbo_Modula_2.pdf, but I found the quality of the scan to be quite poor (many pages badly centered, sometimes a bit truncated), so I have started to re-type some chapters with my little fingers (text attached), in text only format so that they can be read on the Modula-2 system itself... But of course 597 pages is a big task...

I wouldn't want you to separate from a manual that reminds you these years at university, so would there be a chance that you could obtain a better scan of it ?

With such a better quality scan, I could then try some OCR software on it...

In any case, thanks again for sharing your Turbo Modula-2 interest :-)

Best regards,

Fabrice

**Comment by ravn** [comment]
Sorry for not being completely clear.  I am cleaning up in my old things, and I'd very much prefer that it got a new home! I cannot think of a better one than yours given your interest.

**Comment by Oric4ever** [comment]
my email should be revealed with this answer, please send me a private mail, I will answer with my postal address and refund you for the postal costs with paypal...
Thanks again,
Fabrice

**Comment by Oric4ever** [comment]
Hello again, Thorbjørn,

it seems GitHub doesn't reveal my email address despite configured like this, so here is my address so that we can exchange privately: fabrice dot frances at wanadoo dot fr

Best regards,

Fabrice
